# Site settings
title: P & P
company: GrinGrid
homepage: choijiho.com
email: admin@choijiho.com
description: > # this means to ignore newlines until "baseurl:"
  CopyLeft@jiho.choi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: choijiho
linkedin_username: choijiho
twitter_username: choijiho
github_username: choijiho
categories: [programming, and, photograph, angular, nodejs, mean, android]

# Build settings
markdown: kramdown

host: 0.0.0.0
